test minikube

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -1,5 +1,6 @@
 name: "Trigger Integration tests"
 on:
+  pull_request:
   pull_request_target:
     types: [labeled, opened]
     branches:
@@ -7,6 +8,37 @@ on:
       - "releases/*"
 
 jobs:
+  aks-minikube-integration-tests:
+    name: Minikube Integration Tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup Minikube
+        uses: manusa/actions-setup-minikube@v2.4.2
+        with:
+          minikube version: "v1.24.0"
+          kubernetes version: "v1.17.8"
+          driver: "none"
+      - uses: actions/checkout@v1
+      - id: action-npm-build
+        run: |
+          npm install
+          npm run build
+      - id: call-create-secret
+        uses: ./
+        with:
+          secret-name: integration-test-secret
+          secret-type: generic
+          string-data: '{ "testKey": "testValue" }'
+      - id: validate-secret-creation
+        run: |
+          export VAL="$(kubectl get secret integration-test-secret --template {{.data.testKey}}| base64 -d)"
+          if [ "$VAL" = "testValue" ]; then
+            echo "successful secret creation"
+          else
+            echo "failed to read secret after creation"
+            echo "VAL=$VAL"
+            exit 1
+          fi
   aks-integration-tests:
     name: AKS Integration Tests
     runs-on: ubuntu-latest
